#!/bin/bash

mencoder -idx "$1" -ovc lavc -oac mp3lame -o avi_output.avi
mencoder -forceidx "avi_output.avi" -of lavf -oac mp3lame -lameopts abr:br=56 -srate 22050 -ovc lavc -lavcopts vcodec=flv:vbitrate=250:mbd=2:mv0:trell:v4mv:cbp:last_pred=3 -o "$1".flv $1;
